### PR TITLE
update prometheus dependency

### PR DESCRIPTION
**Pull request by happysalada**
update prometheus dependency requirement

### CODE REVIEW

**Comment by deadtrickster** [comment]
Woops, I thought I replied to this... So this is a hybrid lib, therefor rebar3 dependency should be updated too, can you look at this?

**Comment by happysalada** [comment]
@deadtrickster should be good, let me know if anything

**Comment by Kyos** [comment]
@deadtrickster Any news on this ? Or can this be merged and released ? Thanks by advance 😄

**Comment by mjaric** [comment]
Please pull this request

**Pull request merged**
