### PR TITLE
use and append existing compile flags

### PR DESCRIPTION
**Pull request by ghost**
Fix for : https://github.com/deadtrickster/prometheus_process_collector/issues/17

If the system has overridden LDFLAGS - for example, because of a non-standard homebrew install location - then the LDFLAGS flag will not be set correctly (-arch x86_64).

This patch _appends_ the build specific settings, meaning the existing system overrides will be respected.

Personally, I'd leave the optimisation settings (-O3) to the users discression, but that's unimportant for this fix.

### CODE REVIEW

**Comment by ghost** [comment]
Also fixed the elixir compilation failure : 

```                                                                                                                                                              
/code/common/horde_test/ DEBUG=1 mix compile                                                                                                                                      
==> prometheus_process_collector                                                                                                                                                  
make: *** No targets specified and no makefile found.  Stop.                                                                                                                      
could not compile dependency :prometheus_process_collector, "mix compile" failed. You can recompile this dependency with "mix deps.compile prometheus_process_collector", update it with "mix deps.update prometheus_process_collector" or clean it with "mix deps.clean prometheus_process_collector"                                                              
==> horde_test                                                                                                                                                                    
** (Mix) Could not compile with "make" (exit status: 2).                                                                                                                          
You need to have gcc and make installed. Try running the                                                                                                                          
commands "gcc --version" and / or "make --version". If these programs                                                                                                             
are not installed, you will be prompted to install them.
```

The error message is misleading - actual problem is that the makefile is in the c_src directory - setting the parameter 'make_cwd' to "c_src" correctly points it to the Makefile in that directory.

**Comment by ghost** [comment]
Also with regard to the Travis failure - I'm seeing the same kind of error accross a slew of Erlang/Elixir projects - suggest we ignore the erlang 18 fail. 

https://twitter.com/binarytemple/status/1170617945208381441

**Comment by ghost** [comment]
@deadtrickster @happysalada - you like ?

**Comment by deadtrickster** [comment]
Hi, I do indeed. Can you please remove OTP 18 then? Really love green builds

**Comment by ghost** [comment]
> Hi, I do indeed. Can you please remove OTP 18 then? Really love green builds

@deadtrickster Completed - with regards - tya brah

**Comment by deadtrickster** [comment]
Thanks, will push to hex sometime soon

**Pull request merged**
